name: Deploy Maintenance Page

on:
  workflow_dispatch:
    inputs:
      maintenanceMessage:
        description: "Set the maintenance message"
        required: true
        default: "You will be able to use the service soon"

jobs:
  deploy:
    name: Deploy Maintenance Page 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    defaults:
      run:
        working-directory: maintenance-page
    env:
      TF_WORKSPACE: production
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: hashicorp/setup-terraform@v1.3.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.11
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Initialize Terraform
        run: terraform init
      - name: Validate Terraform
        run: terraform validate
      - name: Create resources
        run: terraform apply -auto-approve -var-file=production.tfvars
      - name: Set Message
        run: sed -i 's/${ maintenanceMessage }/${{ github.event.inputs.maintenanceMessage }}/g' html/index.html
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./html/ s3://register-406-beacons.service.gov.uk --delete
